[package]
name = "flora_v8"
version = "142.2.0-flora.3"
description = "Rust bindings to V8 (flora fork)"
readme = "README.md"
authors = ["the Deno authors"]
license = "MIT"
edition = "2024"
repository = "https://github.com/taskylizard/rusty_v8"
include = [
  ".gn",
  "BUILD.gn",
  "Cargo.toml",
  "Cargo.lock",
  "README.md",
  "LICENSE",
  "build.rs",
  "src/**",
  "gen/**",
  "tools/download_file.py",
]

[lib]
name = "v8"

[profile.dev]
# rusty_v8 may miscompile at opt-level=0.
# https://github.com/rust-lang/rust/issues/87215
# https://github.com/rust-lang/rust/issues/75839
# https://github.com/rust-lang/rust/issues/121028
opt-level = 1

[features]
default = ["use_custom_libcxx"]
use_custom_libcxx = []
v8_enable_pointer_compression = []
v8_enable_sandbox = ["v8_enable_pointer_compression"]
v8_enable_v8_checks = []

[dependencies]
bitflags = "2.5"
paste = "1.0"
temporal_capi = { version = "0.1.0", features = ["zoneinfo64"] }

[build-dependencies]
miniz_oxide = "0.8.8"
gzip-header = "1.0.0"
fslock = "0.2"
which = "6"
home = "0"
bindgen = "0.72"

[dev-dependencies]
miniz_oxide = "0.8.8"
gzip-header = "1.0.0"
bytes = "1"
align-data = "0.1.0"
fslock = "0.2"
trybuild = "1.0.96"
which = "6"
home = "0"
rustversion = "1"
bindgen = "0.72"

[[example]]
name = "hello_world"

[[example]]
name = "shell"

[[example]]
name = "process"

# Commented out to avoid conflict with build script
# [[test]]
# name = "build"
# path = "build.rs"

[[bench]]
name = "function"
path = "benches/function.rs"
harness = false

[workspace]
members = ["examples/android"]
